"""empty message

Revision ID: 1a3d611c813c
Revises: 274a186dc3ca
Create Date: 2024-05-20 20:33:40.118280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3d611c813c'
down_revision = '274a186dc3ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private', sa.Boolean(), nullable=True))

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private', sa.Boolean(), nullable=True))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private', sa.Boolean(), nullable=True))

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('private')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('private')

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('private')

    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.drop_column('private')

    # ### end Alembic commands ###
