"""empty message

Revision ID: 215c500fc12c
Revises: 2ef7053298db
Create Date: 2024-04-11 03:12:22.940221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215c500fc12c'
down_revision = '2ef7053298db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_column('reason')

    # ### end Alembic commands ###
