"""Tables schedule

Revision ID: 274a186dc3ca
Revises: 9d7f7f52d5a4
Create Date: 2024-04-13 23:52:40.412729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '274a186dc3ca'
down_revision = '9d7f7f52d5a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_schedule',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('organization_id', 'connection_id')
    )
    op.create_table('project_schedule',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'schedule_id')
    )
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_constraint('organization_ibfk_2', type_='foreignkey')
        batch_op.drop_column('schedule_id')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint('project_ibfk_1', type_='foreignkey')
        batch_op.drop_column('schedule_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('project_ibfk_1', 'schedule', ['schedule_id'], ['id'])

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('organization_ibfk_2', 'schedule', ['schedule_id'], ['id'])

    op.drop_table('project_schedule')
    op.drop_table('organization_schedule')
    # ### end Alembic commands ###
