"""tables

Revision ID: 9d7f7f52d5a4
Revises: 215c500fc12c
Create Date: 2024-04-13 22:02:20.466517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d7f7f52d5a4'
down_revision = '215c500fc12c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_connection',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connection.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('organization_id', 'connection_id')
    )
    op.create_table('project_connection',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connection.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'connection_id')
    )
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_constraint('organization_ibfk_1', type_='foreignkey')
        batch_op.drop_column('connection_id')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint('project_ibfk_3', type_='foreignkey')
        batch_op.drop_column('connection_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connection_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('project_ibfk_3', 'connection', ['connection_id'], ['id'])

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connection_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('organization_ibfk_1', 'connection', ['connection_id'], ['id'])

    op.drop_table('project_connection')
    op.drop_table('organization_connection')
    # ### end Alembic commands ###
